Secondary functions
htmlacademy-javascript/1146869-keksobooking-24 pull request #2
Opened 2021-09-28 16:42 UTC by FarukhIliyev

2021-09-28 16:49 UTC, Spearance requested changes

2021-09-28 16:49 UTC, Spearance commented on js/main.js
> +  return Math.floor(Math.random() * (max-min)) + min;
нет условий если min больше max или если одно из значений меньше 0

2021-09-28 16:49 UTC, Spearance commented on js/main.js
> +function getRandomArbitrary(min, max) {
про function писал в skype, а так в целом то же самое что и в первой функции

2021-09-29 05:33 UTC, FarukhIliyev commented on js/main.js
> +function getRandomArbitrary(min, max) {
виноват, не прочитал в скайпе, уведомления отключены были(

2021-09-29 05:34 UTC, FarukhIliyev commented on js/main.js
> +  return Math.floor(Math.random() * (max-min)) + min;
вроде что то сейчас пишу, но не совсем въезжаю)))

2021-09-29 17:27 UTC, merged